utube:
  apikey: AIzaSyDRV8I51ShYKJKJDbTbQVuJDYQy0yBC6SA
googleSSO:
  id: 416348247465-3lmacilgcghqqdcigu8qcqk803d7ept5.apps.googleusercontent.com
  secret: pv9X9SpkJpfX7p2e4Yp6Wdw5
leetcode:
  temp: j
  endpoints:
    all: https://leetcode.com/api/problems/all/
  query:
    P1: '{"operationName":"questionData","variables":{"titleSlug":"'
    P2: '"},"query":"query questionData($titleSlug: String!) {  question(titleSlug: $titleSlug) {    questionId    questionFrontendId    boundTopicId    title    titleSlug    content    translatedTitle    translatedContent    isPaidOnly    difficulty    likes    dislikes    isLiked    similarQuestions    exampleTestcases    contributors {      username      profileUrl      avatarUrl      __typename    }    topicTags {      name      slug      translatedName      __typename    }    companyTagStats    codeSnippets {      lang      langSlug      code      __typename    }    stats    hints    solution {      id      canSeeDetail      paidOnly      hasVideoSolution      paidOnlyVideo      __typename    }}}"}'
